paths:
  static: ''
  uploads: uploads
timezone: Asia/Jakarta
markdown:
  engine: commonmark
  options: {}
collections_config:
  pages:
    path: ''
    icon: wysiwyg
  admin:
    path: admin
    icon: ad
  data:
    path: data
    icon: data_usage
